package com.example.weatherapijetpack.helpers

const val SHARED_PREFERENCES_NAME = "CITY_SP"
const val BASE_URL = "185ad123caa54d14a2f62329230304"
const val CURRENT = "current"
const val LOCATION = "location"
const val CONDITION = "condition"
const val FORECAST = "forecast"
const val FORECASTDAY = "forecastday"
const val NAME = "name"
const val LAST_UPDATED = "last_updated"
const val TEXT = "text"
const val TEMP_C = "temp_c"
const val ICON = "icon"
const val DATE = "date"
const val DAY = "day"
const val MAXTEMP_C = "maxtemp_c"
const val MINTEMP_C = "mintemp_c"
const val HOUR = "hour"
const val TIME = "time"